version: '3.9'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: npm start
    container_name: 'mdn-bot'
    restart: on-failure
    env_file:
      - .env
    networks:
      - main_net
networks:
  main_net:
    driver: 'bridge'
